version: '3.9'

services:
  mssql:
    container_name: "mssql"
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: on-failure
    ports:
      - 1433:1433
    
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Hobujaama10
      
    volumes:
        - itaxi-volume:/var/lib/mssql/data
      
volumes:
  itaxi-volume:

  

      
